### ISSUE TITLE
illumos (Omni OS) build error involving sim_ether.c

### ISSUE THREAD

**Issue by jayjwa** [simh/simh#1238]
There is a build error on Omni OS in sim_ether.c.

```
$ uname -a
SunOS fatalis 5.11 omnios-r151056-9fd2b931e3 i86pc i386 i86pc
```

```
$ root@fatalis:/opt/simh# gmake microvax3900
lib paths are: /lib/64 /usr/lib/64 /lib/ /usr/lib/
include paths are:  /opt/gcc-14/lib/gcc/x86_64-pc-solaris2.11/14.3.0/include /opt/gcc-14/include /usr/include BIN/unix-build/local/include
using libm: /lib/64/libm.so
using librt: /lib/64/librt.so
using libpthread: /lib/64/libpthread.so /usr/include/pthread.h
using libpcre: /usr/lib/64/libpcre.so /usr/include/pcre.h
using libedit: /usr/lib/64/libedit.so /usr/include/editline/readline.h
using semaphore: /usr/include/semaphore.h
using libdl: /lib/64/libdl.so /usr/include/dlfcn.h
using mman: /usr/include/sys/mman.h
using libpcap: /usr/include/pcap.h
***
*** microvax3900 Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 14.3.0.
*** - Each source module compiled separately.
*** - Summary Compile and Link commands are displayed.
***   Put QUIET=0 on the make command line to see command details.
*** - dynamic networking support using Solaris provided libpcap components.
*** - Local LAN packet transports: PCAP TAP NAT(SLiRP)
*** - Per simulator tests will be run.
***
*** git commit id is 9c20f9ca35c25490d1b5cb25cd1388f436ed9438.
*** git commit time is 2025-12-09T16:43:14-1000.
***
Compiling sim_ether.c into BIN/SunOS-build/vax/sim_ether.o
sim_ether.c: In function '_eth_open_port':
sim_ether.c:2947:22: error: 'FIONBIO' undeclared (first use in this function)
 2947 |       if (ioctl(tun, FIONBIO, &on)) {
      |                      ^~~~~~~
sim_ether.c:2947:22: note: each undeclared identifier is reported only once for each function it appears in
gmake[1]: *** [makefile:3280: BIN/SunOS-build/vax/sim_ether.o] Error 1
gmake: *** [makefile:2685: BIN/vax] Error 2
[16:59] root@fatalis:/opt/simh#
```
The header <sys/filio.h> should be added in sim_ether.c, around the unistd.h or other suitable place. Evidently, illumos and its distros have diverged from Solaris and may require special attention. According to _andyf_ (one of the main illumos guys), one can use \_\_illumos\_\_ to test for the platform in ifdef statements. 

Working:
```
/opt/simh/BIN/microvax3900

MicroVAX 3900 simulator V4.0-0 Current        git commit id: 9c20f9ca+uncommitted-changes
sim> show version
MicroVAX 3900 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 15
    Host Platform:
        Compiler: GCC 14.3.0
        Simulator Compiled as C arch: x64 (Release Build) on Dec 10 2025 at 17:04:02
        Build Tool: simh-makefile-separate-compiles
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.45 2021-06-15) support for EXPECT and IF commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        EditLine Version: 4.2
        Ethernet packet info: NAT, TAP, UDP, PCAP: libpcap version 1.10.5
        Operating System: OmniOS Community Edition v11 r151056d
        OS: SunOS fatalis 5.11 omnios-r151056-9fd2b931e3 i86pc i386 i86pc
        tar tool: tar: s: unknown function modifier
        curl tool: curl 8.16.0 (x86_64-pc-solaris2.11) libcurl/8.16.0 OpenSSL/3.5.4 zlib/1.3.1 brotli/1.1.0 zstd/1.5.7 libpsl/0.21.5 nghttp2/1.67.1
        Not running as root
        git commit id: 9c20f9ca+uncommitted-changes
        git commit time: 2025-12-09T16:43:14-1000
sim> exit
Goodbye
```
Network working:
```
dnping -v -c 4 teostr
PKT: 1      WRITE: 40 READ: 40 
PKT: 2      WRITE: 40 READ: 40 
PKT: 3      WRITE: 40 READ: 40 
PKT: 4      WRITE: 40 READ: 40 
Sent 4 packets, Received 4 packets
```
Why this builds on Open Indiana no problem but doesn't on Omni I don't know. Both have the header file, and OI doesn't care if it's there or not.

**Comment by jayjwa** [comment]
Worse, both my Omni and OI sys/ioctl.h have the same sha1 sum, and both include filio.h at the end. 

There is a difference that might explain it: my system has tun/tap support. 
```
$modinfo | grep tap
270 fffffffff3fd9000   2378 292   1  tap (TUN/TAP driver 1.3.0 10/23/2025)
```
My OI system does not. The idea was to run Omni on the bare metal, then OI and other stuff (this is where SIMH comes in) under it. Thus only my Omni has TUN/TAP as there's no need for OI to have it.

Also, my GCC is a bit newer. In sim_ether.c, around line 2940 there is an \#ifdef for HAVE_TAP_NETWORK. The code that makes the error is in that block. ioctl.h only grabs filio.h if BSD_COMP is defined. If I \#define BSD_COMP _before_ sys/ioctl.h, **then** it builds while only including sys/ioctl.h . 

Here's my pdp11. Note the _Packet transports:PCAP:TAP:NAT:UDP_ line.

```
PDP-11 simulator V4.0-0 Current        git commit id: 9c20f9ca+uncommitted-changes
sim> show version
PDP-11 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 15
    Host Platform:
        Compiler: GCC 14.3.0
        Simulator Compiled as C arch: x64 (Release Build) on Dec 11 2025 at 13:42:18
        Build Tool: simh-makefile-separate-compiles
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.45 2021-06-15) support for EXPECT and IF commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        EditLine Version: 4.2
        Ethernet packet info: NAT, TAP, UDP, PCAP: libpcap version 1.10.5
        Operating System: OmniOS Community Edition v11 r151056d
        OS: SunOS fatalis 5.11 omnios-r151056-9fd2b931e3 i86pc i386 i86pc
        tar tool: tar: s: unknown function modifier
        curl tool: curl 8.16.0 (x86_64-pc-solaris2.11) libcurl/8.16.0 OpenSSL/3.5.4 zlib/1.3.1 brotli/1.1.0 zstd/1.5.7 libpsl/0.21.5 nghttp2/1.67.1
        Not running as root
        git commit id: 9c20f9ca+uncommitted-changes
        git commit time: 2025-12-09T16:43:14-1000
sim> 
```
Looks like BSD_COMP has to be defined before you try to build TAP stuff, else you won't get filio.h out of ioctl.h. Hopefully we get a little closer finding what's exactly going on. 

Sorry about the install issues. A number of people complain about OI installation - there were some permission issues with the live system. I have it running in bhyve under Omni which itself is on AMD hardware and I used the text installer.
